#!/usr/bin/env bash
# Displays "Best school" 10 times, then "bad luck" at 4th and "good luck" at 8th

count=0

while [ $count -lt 10 ]
do
  if [ $count -eq 3 ]
  then
    echo "bad luck"
  elif [ $count -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( count++ ))
done
